build: remove natspec-smells

diff --git a/.github/workflows/natspec.yml b/.github/workflows/natspec.yml
--- a/.github/workflows/natspec.yml
+++ b/.github/workflows/natspec.yml
@@ -1,4 +1,4 @@
-name: Natspec report
+name: NatSpec
 on:
   pull_request:
 
@@ -6,46 +6,24 @@ env:
   FOUNDRY_PROFILE: ci
 
 jobs:
-  natspec-smells:
+  lintspec:
     runs-on: ubuntu-latest
-    permissions:
-      contents: read
-      pull-requests: write
+    outputs:
+      total-diags: ${{ steps.lintspec-action.outputs.total-diags }}
     steps:
-      - uses: actions/create-github-app-token@v1
-        id: app-token
-        with:
-          app-id: ${{ secrets.APP_ID }}
-          private-key: ${{ secrets.APP_PRIVATE_KEY }}
-          owner: ${{ github.repository_owner }}
-          repositories: "universal-router,usdn-contracts"
-
       - uses: actions/checkout@v4
+      - name: Check NatSpec
+        id: lintspec-action
+        uses: beeb/lintspec@main
         with:
-          submodules: recursive
-          token: ${{ steps.app-token.outputs.token }}
+          fail-on-problem: "false" # we handle failure manually to be able to trigger the notification
+          version: "0.4.1"
+      - name: Fail on findings
+        if: ${{ steps.lintspec-action.outputs.total-diags > 0 }}
+        run: exit 1
 
-      - name: Install Foundry
-        uses: foundry-rs/foundry-toolchain@v1
-        with:
-          version: nightly
-
-      - name: Install Node 20
-        uses: actions/setup-node@v4
-        with:
-          node-version: 20
-
-      - name: Add app token to git config for soldeer to use
-        env:
-          APP_TOKEN: ${{ steps.app-token.outputs.token }}
-        run: |
-          git config --global url."https://x-access-token:$APP_TOKEN@github.com/".insteadOf "git@github.com:"
-      - name: Install deps
-        run: npm ci && forge soldeer install
-
-      - name: Report natspec smells findings
-        uses: SmarDex-Ecosystem/natspec-smells-action@v2
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          working-directory: ./
-          update-comment: true
+  notify-on-failure:
+    needs: lintspec
+    if: ${{ always() && needs.lintspec.outputs.total-diags > 0 }}
+    uses: ./.github/workflows/notify_failure.yml
+    secrets: inherit
